/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anyvr_app_lemon_jni_Opus */

#ifndef _Included_anyvr_app_lemon_jni_Opus
#define _Included_anyvr_app_lemon_jni_Opus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    decode
 * Signature: (J[BII[BIII)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    decoder_create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_anyvr_app_lemon_jni_Opus_decoder_1create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    decoder_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_anyvr_app_lemon_jni_Opus_decoder_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encode
 * Signature: (J[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_get_bandwidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1get_1bandwidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_get_bitrate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1get_1bitrate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_get_complexity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1get_1complexity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_set_bandwidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1set_1bandwidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_set_bitrate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1set_1bitrate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_set_complexity
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1set_1complexity
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_set_max_bandwidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1set_1max_1bandwidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     anyvr_app_lemon_jni_Opus
 * Method:    encoder_set_packet_loss_perc
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_anyvr_app_lemon_jni_Opus_encoder_1set_1packet_1loss_1perc
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
